export const genres = [
    { genre: 'Action', clicked: false },
    { genre: 'Animation', clicked: false },
    { genre: 'Biography', clicked: false },
    { genre: 'Comedy', clicked: false },
    { genre: 'Crime', clicked: false },
    { genre: 'Crime Drama', clicked: false },
    { genre: 'Dark Comedy', clicked: false },
    { genre: 'Documentary', clicked: false },
    { genre: 'Drama', clicked: false },
    { genre: 'Fantasy', clicked: false },
    { genre: 'Horror', clicked: false },
    { genre: 'Legal Drama', clicked: false },
    { genre: 'Musical', clicked: false },
    { genre: 'Mystery', clicked: false },
    { genre: 'Film Noir', clicked: false },
    { genre: 'Gangster', clicked: false },
    { genre: 'Western', clicked: false },
    { genre: 'Romance', clicked: false },
    { genre: 'Sports', clicked: false },
    { genre: 'Thriller', clicked: false },
    { genre: 'Contemporary Fantasy', clicked: false },
    { genre: 'Historical Fiction', clicked: false },
    { genre: 'Psychological Thriller', clicked: false },
    { genre: 'Science Fiction', clicked: false },
  ]